user_story_mapping.md

What does this PR do?
Fixes a small typo in User Story Mapping
Which tests illustrate how this code works?
n/a
Is there a relevant Issue open for this?
n/a
Are there any other relevant resources that should be reviewed as well?
n/a
Who would you like to review this?
should be able to be immediately merged. @sherl0cks as an FYI.

fixed small typo

---

content/practices/why-is-defined.md
content/stages/approach.md
content/stages/discovery.md
content/waypoints/goal-or-problem-statement-defined.md
docs/index.html
docs/index.xml
docs/practices/index.html
docs/practices/index.xml
docs/practices/why-is-defined/index.html
docs/sitemap.xml
docs/stages/approach/index.html
docs/stages/discovery/index.html
docs/stages/index.xml
docs/waypoints/assumptions-identified/index.html
docs/waypoints/assumptions-prioritized/index.html
docs/waypoints/goal-or-problem-statement-defined/index.html
docs/waypoints/index.html
docs/waypoints/index.xml
docs/waypoints/why-is-defined/index.html
layouts/partials/entry/practice-meta.html

What does this PR do?
Add content for discovery and approach stages. Fixed location of "why-is-defined" as it is a practice not a waypoint.
Is there a relevant Issue open for this?
n/a
Are there any other relevant resources that should be reviewed as well?
Who would you like to review this?
@rdebeasi @sherl0cks

update content for approach and discovery. moved why page into practices

---

content/waypoints/assumptions-identified.md
content/waypoints/assumptions-prioritized.md
docs/index.xml
docs/waypoints/assumptions-identified/index.html
docs/waypoints/assumptions-prioritized/index.html
docs/waypoints/index.xml

What does this PR do?
add in content for assumptions-identified and assumptions-prioritized
Is there a relevant Issue open for this?
n/a
Are there any other relevant resources that should be reviewed as well?
n/a
Who would you like to review this?

add content for assumptions waypoints

---

content/practices/agile-agenda.md
content/practices/discovery-session.md
content/practices/impact-mapping.md
content/practices/realtime-retrospective.md
content/practices/social-contract.md
content/practices/user-story-mapping.md
content/practices/vsm-and-mbpm.md
content/waypoints/operational-constraints-identified.md
docs/index.html
docs/index.xml
docs/practices/agile-agenda/index.html
docs/practices/discovery-session/index.html
docs/practices/impact-mapping/index.html
docs/practices/index.html
docs/practices/index.xml
docs/practices/page/2/index.html
docs/practices/realtime-retrospective/index.html
docs/practices/social-contract/index.html
docs/practices/user-story-mapping/index.html
docs/practices/vsm-and-mbpm/index.html
docs/sitemap.xml
docs/waypoints/index.xml
docs/waypoints/operational-constraints-identified/index.html

What does this PR do?
Adds content for Operational Constraints Waypoint. Fixes typos in spelling. 
Add Social Contract Practice!
Is there a relevant Issue open for this?
#21
Are there any other relevant resources that should be reviewed as well?
Who would you like to review this?
@sherl0cks @rdebeasi

Add Social Contract as a Practice

---

content/practices/event-storming.md
content/practices/social-contract.md
docs/practices/event-storming/index.html
docs/practices/social-contract/index.html

Guys - could one of you have a quick scan over these fixes please? Have tested locally.

Fix broken links

---

content/practices/agile-agenda.md

prep change to content for how this practice fits into v2 of OPL

updated phase data

---

content/practices/event-storming.md

identify this practice as an "Outcome" practice.

update for new categories

---

content/practices/burndown.md

Identified how this practice fits in with the new categories. Resolved a title issue for the "How to" description.

Updated phase section

---

content/practices/retrospectives.md

updated in prep for the mobius loop integration

update for the categories

---

content/practices/social-contract.md

updated for the integration with the mobius loop

update the category

---

config.toml
layouts/partials/footer-custom.html
layouts/partials/share.html
layouts/practices/single.html
static/css/custom.css

**What does this PR do?**
This PR is to add some basic chat features to the practice pages. Users will login with their GitHub account. Members of the org `openpracticelibrary` will be able to admin the groups etc too.
Resolves #163

Adding gitter chat to each practice

---

static/admin/config.yml

** What does this do?  **
#233 by lowercasing the values of the areas on the loop

Lowercase of metadata values #233

---

config.toml
layouts/partials/author.html
static/css/custom.css

This PR is still WIP; and needs some thinking. It's a rework to make the author info match the designs.

Updates to the author flow to match design

---

content/practices/agile-agenda.md
content/practices/burndown.md
content/practices/event-storming.md
content/practices/impact-mapping.md
content/practices/realtime-retrospective.md
content/practices/social-contract.md
content/practices/start-at-the-end.md
content/practices/stop-the-world-event.md
content/practices/team-sentiment.md
content/practices/team-shared-history.md
content/practices/user-story-mapping.md
content/practices/visualisation-of-work.md
content/practices/vsm-and-mbpm.md

Fixes a load of missing info needed for doing one of the other tasks
I added the missing information? ie where in the loop and author data

FIX a bunch of metadata on practices

---

content/practices/retrospectives.md
content/practices/visualisation-of-work.md
layouts/partials/practice-heading.html
layouts/practices/single.html
static/admin/config.yml
static/css/custom.css
static/css/old.css

#245  
Styling the heading should be done as in the designs. This PR should bring us closer to that.

Styling the article heading as per design #245

---

config.toml
layouts/partials/share.html
static/css/custom.css

Resolves #246 - tidy up css
Tidy up the base CSS to fix typefonts etc

Switch out primary font, image and colours

---

static/admin/config.yml

Takes us closer to solving #153
This PR adds a new content type to our CMS, `how-to`. It collects data as per the designs of the cards on the Practice page

how-to cms entry

---

static/admin/config.yml

Value is missing from foundation on mobius area
I've added in the value for the dropdown

Fix value not coming through

---

static/admin/index.html

this issue resolves the user workflow being confusing
Until we have a better fix upstream, the community has decided for now we'll hide / remove the button

Hide  publish bar in CMS land

---

DEVELOPING.md

Resolves #208
Add the process that we discussed, along with some context, to the developing guide.
Before this is merged, we should:
- Double-check with the community
- Decide whether we want this content to apply to all changes, or just to dev changes

Add optimistic merging guide

---

static/admin/config.yml

Resolves  #296 or at least some of it
I have added to the body of each practice the following leading text
```
```

Add default heading for articles

---

content/practice/daily-standup.md
data/content/author/sandraarps.toml

Sandra had not been set up as an author so builds were failing for new content she has written. I have created her as an author in CMS and merged into staging. This PR will make that change live.

Put latest merge into production

---

static/admin/config.yml

Closes #357 
Now that https://github.com/netlify/netlify-cms/pull/1429 has been merged I've updated our CMS config to give guidance to what should be put in each field.

Add hints to fields in the CMS

---

content/page/about.md

Issue #240
Add the description of a practice

Update about.md to add the description of a practice

---

content/practice/force-field-analysis-force-field-map.md
content/practice/hmw.md

new practice creation
create new practice of How Might We (HMW)

HMW Practice creation

---

content/practice/hmw.md
content/practice/whole-product-plotting.md

new practice creation
practice on Whole Product Plotting

Whole Product Plotting Practice creation

---

content/practice/design-the-box.md
content/practice/how-now-wow-prioritization-matrix.md

new practice creation
create the how-now-wow prioritization practice

new how-now-wow practice

---

content/practice/how-now-wow-prioritization-matrix.md
content/practice/news-headlines-aka-cover-story.md

new practice creation
new News Headlines practice created.

new News Headlines practice

---

content/practice/impact-mapping.md
content/practice/news-headlines-aka-cover-story.md

n/a
Adding content for context on expressing intent from David Marquet speech.

update content to Impact Mapping

---

content/practice/impact-mapping.md
content/practice/priority-sliders.md

adding in additional content for explaining Why for the Priority Sliders practice.

add some why for Priority Sliders

---

content/practice/design-of-experiments.md
data/content/author/darcief.toml

new author!!!

---

content/practice/design-sprint.md

fix raw iframe being displayed. embed iframe in markdown.

embed iframe in markdown

---

content/practice/ui-design-workshop.md

Riley and I worked together on this practice, but is name isn't listed.
... add Riley's name.

Add Riley to UI Design Workshop

---

content/practice/vsm-and-mbpm.md

- Fix some minor grammatical issues

Minor updates to VSM and MBPM page

---

content/practice/social-contract.md

New Practice "Start-with-Why"

---

content/practice/open-decision-making.md

The build failed in #744, but this change was merged anyway, causing all subsequent builds to fail.
Remove the invalid `perspectives` metadata that caused the build failure.
**Next steps**
- Merge staging into the open PR branches so that the builds succeed.
- Consider requiring a successful build before a PR can be merged.
@springdo @tdbeattie

Remove invalid perspective data

---

package-lock.json
package.json

Updates the versions for a underscore.string, lodash, js.yaml in package.json
Multiple medium to high severity vulnerabilities exist in the project. Quick PR to update them

Fix a few security vulnerabilities

---

content/practice/crazy-8s.md
data/content/author/rhdojun.toml

Merge in new author

---

content/practice/hmw.md
content/practice/retrospectives.md

Updated HMW title to spell out full term "How Might We"

Updated HMW Title

---

content/practice/lean-canvas.md
content/practice/opportunity-solution-tree.md

Fix grammatical errors in Lean Canvas

Grammatical Updates to Lean Canvas

---

content/practice/event-storming.md

Fix phrasing

---

build.sh
google/google258e983a9db81826.html

Adding Google Verification for SEO purposes - to set up Google Search Console.

google verification added for SEO

---

src/components/practicePage/PageBody/HowDo.js
src/components/practicePage/PageBody/ResourcesWeLove.js
src/components/practicePage/PageBody/WhatIs.js
src/components/practicePage/PageBody/WhyDo.js
src/components/practicePage/PageMenu/SocialLinks.js
src/components/practicePage/index.js
src/components/shared/Collection/index.js
src/components/shared/Drawer/index.js
src/components/shared/PracticeCards/PracticeCardGrid.js
src/components/shared/PracticeCards/PracticeCardTitle.js
src/pages/404.js
src/pages/index.js

Fix the 404 width found on preview.
Also cleaned up the ESLint errors in the console, maybe not in the best way, but cleaned them for now.

fix(404): fix 404 page width and cleanup ESLint errors

---

gatsby-node.js
src/components/allPractices/FilterBar/FilterTags.js
src/components/allPractices/index.js
src/templates/tags-template.js
static/admin/config.yml

Filter tags pages

---

src/components/About/HistoryValues.js
src/components/Learn/CuratedPractices.js
src/components/Learn/Explore.js
src/components/Learn/ProcessModel.js
src/components/practicePage/PageBody/ResourceListItem.js
src/components/shared/BodyFooter/FooterIconSection.js
src/components/shared/BodyFooter/FooterLinkSection.js
src/components/shared/Drawer/FooterList.js
src/components/shared/Drawer/ListItems.js
src/components/shared/PracticeCards/CoverImage.js
src/components/shared/PracticeCards/PracticeCardTitle.js
src/components/shared/PracticeCards/Subtitle.js
src/pages/404.js
src/pages/learn.js
src/templates/tags.js

https://github.com/openpracticelibrary/opl-fe/issues/210

fix(learn): button and links

---

src/pages/about.js
src/templates/practice-page.js

added drawer back to about page

---

src/components/shared/Drawer/Footer.js
src/components/shared/Drawer/ListItems.js
src/components/shared/Drawer/index.js

updated links

---

src/components/practicePage/PageIntro/ContributedBy.js

don't show authors that aren't in data/authors

---

src/pages/learn.js

added helmet content to learn page

---

package.json
static/admin/config.yml

fixing slug creation per netlify cms docs

---

gatsby-config.js

added tracking ID to gatsby plugin

---

src/pages/practice/code-review.md
static/admin/config.yml

make templateKey required so cms adds to frontmatter

---

CODE_OF_CONDUCT.md
package.json
src/pages/page/contribution-guide.md

moved all email refs to info@openpracticelibrary.com

---

.github/workflows/end-to-end-testing.yaml
.gitignore
cypress.json
cypress/integration/practice_pages_spec.js
cypress/integration/sample_spec.js
cypress/plugins/index.js

E2E Tests GitHub Action to Cypress Dashboard

---

src/components/Layout.js
src/pages/about.js
src/pages/index.js
src/pages/learn.js
src/templates/additional-page.js
src/templates/blog-template.js
src/templates/practice-page.js
src/templates/tags-template.js

adding helmet content for social share

---

src/components/Layout.js
src/pages/about.js
src/pages/blog/index.js
src/pages/index.js
src/pages/learn.js
src/templates/additional-page.js
src/templates/blog-template.js
src/templates/practice-page.js
src/templates/tags-template.js

use icon, not mediaGallery link

---

static/admin/config.yml

**What issue does this PR solve?**'
- Open PRs on `master` branch.
- Preview --> Production flow
> "Shift left, and other such buzzwords"
>                                     - Lucas Allmon

moved PRs to master

---

src/components/Layout.js
src/components/Learn/ProcessModel.js
src/components/allPractices/index.js
src/components/shared/Drawer/DrawerFooter.js
src/components/shared/Drawer/ListItems.js
src/components/shared/Drawer/index.js
src/components/shared/MobiusLoopHero/index.js
src/pages/learn.js

Should help resolve #1208 and resolve #1209

feature(mobile): basic pass for mobile responsiveness

---

src/components/shared/PracticeCards/PracticeCard.js

fix(layout): optimized images

---

cypress/integration/event_storming_spec.js
src/components/allPractices/FilterBar/FilterTags.js
src/components/practicePage/PageIntro/TitleAndSubtitle.js
src/components/shared/Search/SearchContainer.js

included detailed test for event storming

---

cypress/integration/event_storming_spec.js

fix(test): flaky e2e test

---

netlify.toml

testing removing gatsby cache plugin

---

.github/workflows/end-to-end-testing.yaml

updated timeout

---

.github/workflows/end-to-end-testing.yaml
netlify.toml

removing cache

---

src/components/practicePage/PageBody/index.js

fix(discuss): change text

---

src/pages/practice/metrics-based-process-mapping.md

adding template key field to mbpm

---

cypress/integration/mobius_loop_spec.js

removing tests until fix is found

---

.github/workflows/autoupdate.yaml

workflow to update prs when merges made to master branch

---

src/pages/practice/metrics-based-process-mapping.md
src/pages/practice/new.md

Added missing templateKeys

---

src/templates/additional-page.js

Solves issue #1464 
Add button to page template and displaying based on the page title: Contribution Guide.

Add Call To Action button in Contribution Guide

---

src/pages/practice/expand-and-contract-pattern.md

Fix expand contract practice not visible

---

src/components/shared/Drawer/ListItems.js

This PR resolves #1598 
#1598 identifies an incorrect path to create a new practice. This PR corrects the path.

Correct path for creating a new practice

---

static/_redirects

Hopefully - this is an easy fix for #1889
Fixed the URL for @tom-geraghty's practice on measuring psychological safety, but need to put in a perm redirect from old to new.  Hopefully this does the trick!

Adds a 301 redirect from /new to /m-p-s

---

src/components/shared/BodyFooter/index.js

https://github.com/openpracticelibrary/openpracticelibrary/issues/1891
Add missing LinkedIn logo to footer of page.

Add LinkedIn icon

---

src/components/About/Contributors.js

https://github.com/openpracticelibrary/openpracticelibrary/issues/1922
The numbers are currently hardcoded and manually updated as and when they change. Till the automatic update feature gets implemented, manual updates are needed. A separate issue is open for automating this.
https://github.com/openpracticelibrary/openpracticelibrary/issues/1921

Updated stats and author nodes.

---

src/pages/practice/1-2-4-all.md

@kattekrab  / @ckavili this was from my messing about... Turns out in the workflow in the CMS 🥁 
I CAN DELETE practices ..... Thought that was disabled but now Im not so sure. I am an admin on the repo anyways so think this is an exception. Would be great if we can test again though with a user who's not an admin in teh OPL org.....

🐉 FIX - delete practice while checking perms 🐉

---

src/pages/practice/1-2-4-all.md
static/admin/config.yml

Fix messing around with workflow

---

src/pages/blog/open-decision-framework.md
src/pages/blog/red-hat-multiplier.md
src/pages/blog/the-open-organization-definition.md
src/pages/practice/grow-model-for-1-1-coaching.md
src/pages/practice/open-decision-framework.md
src/pages/practice/open-decision-making.md

#2120 
Updated the author file, this change updates blog and practice pages to refer to the updated author file.

fixes shabs github id #2120

---

.github/workflows/end-to-end-testing.yaml

No issue created
Fix Google Chat integration

Fix GitHub Action typo

---

src/components/About/Contributors.js

practices from 207 to 220
contributors from 124 to 137

Update numbers on Contributors.js 

---

src/components/allPractices/FilterBar.js
src/components/shared/MobiusLoopHero/index.js
src/gatsby-theme-material-ui-top-layout/theme.js

#2062 
Changed mobius loop colours to match upstream

Update mobius loop colours

---

src/components/allPractices/FilterBar.js
src/components/shared/MobiusLoopHero/index.js
src/gatsby-theme-material-ui-top-layout/theme.js
src/utilities/mobuisContent.jsx

#2228 
#2229 
Updated mobius loop colours and labels

Mobius colours

---

src/components/shared/BodyFooter/index.js

#2231
We are no longer active on twitter or instagram.

Removes twitter and instagram logos from footer

---

package-lock.json
package.json

Reverts openpracticelibrary/openpracticelibrary#2273
It broke something

Revert "Bump cross-spawn, password-prompt, gatsby-cli and cypress"

---

DEVELOPING.md

#2263 
Similar to PR #2275 
We suggested people get in touch via Gitter - but it no longer exists, so I've changed that to say "raise an issue in GitHub"
Again,  🙏 Thanks to @Moosh-be 🙏 for raising issue https://github.com/openpracticelibrary/openpracticelibrary/issues/2263

Update DEVELOPING.md to remove Gitter ref.
