content/page/way-of-working.md
Link was missing the s on /practices/
=> Fixing broken link to stop-the-world page

README.md
Add a bit more information, but more importantly, link to the phrase "open practice library" to the user-facing site. (Right now, the first Google result for "open practice library" is our GitHub repo, followed by the markdown for the about page, followed by... our config file?)
=> Rephrase readme intro text.

docs/404.html, docs/about/index.html, docs/categories/index.html, docs/css/custom.css, docs/index.html, docs/js/search.js, docs/js/searchButton.js, docs/page/index.html, docs/practices/agile-agenda/index.html, docs/practices/burndown/index.html, docs/practices/event-storming/index.html, docs/practices/impact-mapping/index.html, docs/practices/index.html, docs/practices/page/2/index.html, docs/practices/prep-week/index.html, docs/practices/realtime-retrospective/index.html, docs/practices/retrospectives/index.html, docs/practices/social-contract/index.html, docs/practices/start-at-the-end/index.html, docs/practices/stop-the-world-event/index.html, docs/practices/team-sentiment/index.html, docs/practices/user-story-mapping/index.html, docs/practices/visualisation-of-work/index.html, docs/practices/vsm-and-mbpm/index.html, docs/search/index.html, docs/tags/index.html, layouts/partials/nav/menus/main.html, static/css/custom.css, static/js/search.js, static/js/searchButton.js
@rohitmusti, do the changes below look okay to you? If so, I'll merge this branch into the `search` branch and then merge that into `master`. If you have any questions, just let me know! :smile: 
---
- Fix bug that prevented search result links from working
- Make the search box and button a bit subtler (smaller, lighter hover state, right aligned)
- Prevent search from wrapping to a second line on the "practices" page
- Prevent search button and search field from getting separated at some screen sizes
- Code style changes
- Don't use `!important`
- Use kebab-case for classes and IDs.
- Use classes for styling and IDs for JS hooks. 
- See [Specifics on specificity](https://css-tricks.com/specifics-on-css-specificity/) for more info.
This PR includes a Hugo rebuild. For just the code …
=> Search fixes

.gitignore
simple fix to also ignore vi/vim swap files.
=> adding vim swp files to the .gitignore

content/_index.md, content/page/about.md, content/practices/event-storming.md
As this repo has been moved to a different github org I've made some fixes to point to the new github organisation in the links in the source.
=> fixes to urls

.gitignore, build.sh, config.toml, netlify.toml
- Use the correct domain in our config. (This isn't a problem for now but could break if we use absolute URLs.)
- Use the `public` folder rather than the `docs` folder. (GitHub pages required `docs`, but a more common pattern for our use case is to use `public`. That's also Hugo's default.)
=> Update configuration for new setup

content/page/about.md
Currently, it is spelled as 'Jex' and it should be 'Jez'.
=> Fix typo in the name of Jez Humble

layouts/_default/single.html, layouts/page/single.html, layouts/practices/single.html
**what does this PR do?**
* Fixes the fact that all practice pages were being set as the _default single page. 
* Added a `practices` folder to the layout which is the styling etc for all practices now. 
* Removed the author stuff from default page type
* Fixed the what to read next by removing it from the `Page` type
=> Suggestions and page type fix

config.toml
**What does this do?**
Fixes the url for the gitter room in the menu as we should now point to the new non hyphenated address.
=> FIX - updated URL for the chat in the menu

content/practice/agile-agenda.md, content/practice/burndown.md, content/practice/event-storming.md, content/practice/impact-mapping.md, content/practice/retrospectives.md, content/practice/social-contract.md, content/practice/start-at-the-end.md, content/practice/team-sentiment.md, content/practice/user-story-mapping.md, content/practice/visualisation-of-work.md, content/practice/vsm-and-mbpm.md
Resolves #285 
We updated `practices` to be `practice` in our page types and paths, which caused existing links to `practices` to break. Updating those links to use `practice` fixed the problem.
I also removed a link to "chartering", which was removed a while back when we got rid of Waypoints.
=> Fix broken internal links

static/admin/config.yml
Resolves #270
I added two fields to the CMS, one for weight and one for menu. Both are not required fields. I've set the Menu to be a dropdown with a true/false and value of the item is `main`. Weight has a regex against it for `0 - 9`
=> Config change to CMS to fix #270

static/css/custom.css
Resolves #308
Over flow of image is chopped off using object fit. This applies to the tiles and the jumbotron image
=> set max height to chop images to big for page

static/admin/index.html
This helps move towards #349 but does not resolve it.
We still have styles for 1.0, even though 2.0 moved to inline styles. This is confusing and slows down page loads. Solution: remove the 1.0 styles (which don't do anything now) as well as the styles to hide the publish button (which don't work with 2.0).
=> Remove Netlify CMS stylesheets

CODE_OF_CONDUCT.md
Adds the reporting email address proposed in #176
- @mtakane set up a forwarding address using forwardmx.io, and I set up the appropriate DNS records in Netlify DNS. We then confirmed that emails actually made it through to Matt.
Before we merge, we should:
- Change the password on the forwardmx.io account
- Securely share the password with the maintainers/moderators
- Update the forwarding destination to include preferred email addresses for the moderators (right now it's just Matt's personal email).
- Do one final test to ensure that everyone on the list receives emails sent to that address.
=> Update reporting email

static/admin/index.html, static/admin/previews.js
Hey folks - loving the project here, really glad you're using Netlify CMS for it! I took the liberty of creating a preview template for your Practice collection, hope it helps. Here's a [preview](https://deploy-preview-384--openpracticelibrary.netlify.com/admin/#/collections/practice/entries/agile-agenda).
Hopefully we can get a solution to the [media issue](https://github.com/netlify/netlify-cms/issues/1344#issuecomment-407560119) going soon 🤞
When creating or editing a new Practice in the CMS, the preview pane is unstyled and doesn't reflect the actual output.
It's always helpful to see what the actual output is when editing content. For example, it may not be obvious which fields are necessary to make …
=> add preview template for practice collection

static/js/search.js
Resolves #364 
Problem: When you search for something, the back button doesn't take you from the search results to the previous page.
Solution: Use `pushState` instead of `replaceState`.
=> Fix back button on search

layouts/partials/home-content.html
Signed-off-by: Clement Verna <cverna@tutanota.com>
Currently it is difficult to find the button to add a new practice, this button is place at the bottom of the page.
This commit move the `Add new practice` button to the top of the
page bellow the `Our Mission` statement. This will make it easier for new contributor to contribute.
=> Make it easier to contribute.

static/admin/config.yml
Right now, perspective is a mandatory field. There are only two perspectives, so there are plenty of practices that don't have a corresponding perspective. It's not possible to edit such practices without adding an unnecessary perspective. This came up in #534.
Add `required: false` to the config for this field.
=> Make perspective field optional

config.toml, content/page/about.md, content/page/cms.md, content/page/contribute.md, content/page/contributing.md, content/page/editorial.md, content/page/home.md, content/page/search.md
See below.
Contributing instructions were spread across the contributing page, the contributing markdown file, and the about page. I consolidated this info into the contributing page. The result was kind of long, so I broke it into "editorial" and "CMS" pages. `CONTRIBUTING.md` is now just a copy of the contributing page. Resolves #518.
The new "editorial" page has definitions for practices and perspectives. Resolves #519. Resolves #520.
I bumped "contributing" up so that it's listed along other internal links, and put perspectives right before it.
Finally, I removed the "just enough" paragraph from the About page, because we've started adding how-tos and other "more detailed content."
We now have enough …
=> Reorganize and expand contributing guide

netlify-setup.md, static/admin/index.html
Resolves this console warning:
> You seem to be loading Netlify CMS by fetching `dist/cms.js` from a CDN. That file is deprecated and will be removed in the next major release. Please use `dist/netlify-cms.js` instead.
Resolves #559.
We were pointing to `dist/cms.js`. We are now pointing to `dist/netlify-cms.js`.
=> Point to the new location for Netlify CMS JS

layouts/_default/single.html
Resolves #689: Some practices without perspectives have blank "this practice is part of..." text.
Netlify CMS creates an empty array when the `perspectives` field is left empty. We were rendering the text on any practices where that field is set - even if the field is empty. This problem didn't affect old practices, but it did affect new ones.
Solution: check if the `perspectives` is truthy (nil or an empty array) instead of checking whether it's set.
Does this look ok, @springdo ?
=> Fix blank "this practice is part of..." text

layouts/_default/single.html, layouts/partials/author.html
If an author is listed in a practice but that author doesn't exist in `data/content/author`, the build will fail. This problem affects most new authors - someone has to add the new author in a separate PR before his or her contributions can go through.
Resolves #204.
Additionally, coauthors are not comma-delimited. The "co-authors" text will appear even if there is only a single author.
Resolves #523.
For each author that isn't in `data/content/author`, build a simple dictionary using the author's GitHub username as the title. That way, we can still show the author's name and pass the build.
Adding the username of a nonexistent GitHub user will cause the author's website link and author image to go to an …
=> Fix byline display and build problems

content/practice/start-with-why.md
Currently the live site is showing a dead image link for the start but why practice when it's displayed in a list.
Currently the live site is showing a dead image link for the start but why practice when it's displayed in a list. This is because it and the jumbotron are both pointing to an image that ends in webp which doesn't display for icons. This changes the icon image link to a png which will show.
=> Quick fix to get the icon of "start with why" to show succesfully

build.sh
This fixes #1020 
build script is generating warning messages when converting images whose filename contain spaces 
The problem was caused by path reference in variables in the build script. Quoting the variables in command lines solves the problems.
=> Fixing image path reference issue when converting images in build script

src/components/practicePage/PageMenu/SocialLinks.js, src/components/practicePage/PageMenu/index.js, src/components/practicePage/index.js
Makes the practice page more responsive
- Practice Page menu bar looks awful on mobile
- Hide the page ref links on mobile screens
- Removed `Like` button for now, can restore easily if we want it to work in `next` version.
=> hide menu ref links on mobile, remove like button for now

src/pages/practice/parking-lot-car-park.md, src/pages/practice/relative-estimation.md, src/pages/practice/risk-issue-management.md, static/admin/config.yml
- Risk Issue Management
- Parking Lot
- Relative Estimation
Also, added the Facilitation Details section back to the netlify cms schema, so they can be edited or added to new practices. These still aren't displayed in `next` and aren't part of the v3 schema, but we can keep it around in case we're asked to put it back.
=> fixed tags and format for 3 practices

src/components/practicePage/PageBody/index.js
This PR resolve the issue [#1288](https://github.com/openpracticelibrary/openpracticelibrary/issues/1288), a typo in the What Is title in practice page template
Added a space in What Is tittle in the Practice Page template.
=> :bug: Fixed What Is title typo (Issue #1288)

src/components/shared/PracticeCards/PracticeCard.js
Fix #1326 
Tested on Chrome and Firefox -- working.
Wrapped Practice Card Grid items with Gatsby Links and removed text-decoration.
=> Ability to right click and open in new tab for practice cards

README.md
#1345 - The README.md points to a nonexistent openpracticelibrary.com page
I also noticed that the README points to about.md, which no longer exists.
`Contributing guide` - Changed link to point to https://openpracticelibrary.com/page/contribution-guide
`About.md` - Reworded slightly and changed link to point to https://openpracticelibrary.com/about
=> #1345/fix contribute link readmemd

src/components/practicePage/PageBody/MediaGallery.js, src/components/practicePage/PageBody/ResourceListItem.js, src/components/practicePage/PageBody/Resources.js
Fixes #1334 
It also fixes an unreported bug with the exception handling the the links url field for "Links we love" and "Media Gallery" links.
A user cannot type in the link url as it expects the url to be copied and pasted only.
=> Fix add links we love

src/components/shared/BodyFooter/index.js, src/components/shared/Drawer/DrawerFooter.js, src/pages/practice/candy-or-swag.md, src/pages/practice/continuous-delivery.md, src/pages/practice/continuous-deployment.md, src/pages/practice/continuous-integration.md, src/pages/practice/decision-jam.md, src/pages/practice/lean-coffee.md, src/pages/practice/realtime-retrospective.md, src/pages/practice/retrospectives.md, src/pages/practice/t2r2-talk-type-read-review.md, src/pages/practice/the-big-picture.md
Site podcast links are all to Apple Podcasts, which is not particularly usable for non-Apple users who just want an RSS feed.
See #1730 
Change the links to Anchor.fm instead, which is where Apple Podcasts gets the feed from anyway, and which gives links to Apple Podcasts, several other podcast services, and a plain RSS feed.
=> Use Anchor.fm podcast links

src/components/shared/Drawer/DrawerFooter.js
Fixes #1729
@ajdlinux filed an issue noting the feedback link in the menu was pointing to a closed form.  
It was not possible to re-open the form due to a missing folder. Rather than spending more time trying to untangle that, I created a new form instead.  This PR updates the link to point to the new form.
=> Points DrawerFooter.js to new Feedback Form

src/components/practicePage/PageBody/Resources.js
Fixes #1753
The issue was due to an out-of-index access error from accessing the first element of an empty array, when attempting to render a practice page.
The fix was to simply add a check, to make sure the array wasn't empty before attempting to access the first value in the array.
=> fix: Allow empty resource lists

static/admin/config.yml
Summary
Updated hint to ensure author is displayed on practices. 
Explanation 
GitHub usernames listed in Netily must exactly match GitHub. If they do not match, the author will not appear on the practice. For example, if I list rohandr, but in GitHub my username is RohanDr, the practice will not display me as an author. The hint has been updated to reflect this new advice. 
Addresses 
https://github.com/openpracticelibrary/openpracticelibrary/issues/1833
=> Amend author hint

src/components/shared/BodyFooter/index.js
In order to qualify for an opensource license, we need to link to netlify
=> Adds 🔗 link 🔗  to netlify in the footer

src/components/shared/BodyFooter/index.js
2nd try at adding link to netlify to the footer so that we can apply for opensource licence.
First attempt failed because I didn't use JS syntax.
=> 2nd attempt to add netlify link

.github/workflows/end-to-end-testing.yaml
Issue to be raised
Currently the only way the OPL maintainers are aware of failed builds is with a legacy Slack integration.
This PR adds Google Chat integration.
It also cleans up the `end-to-end-testing.yaml` file
=> Add Google Chat integration

.github/workflows/end-to-end-testing.yaml
No issue created
Fixes GitHub Action version, which was released without the `action.yml` file
=> Update send-google-chat-webhook GitHub Action version

src/components/shared/BodyFooter/index.js
Extend community links with Open Collectiva and RedBubble.
This PR fixes the #2223 issue adding into the community links both references.
Sell Icon - https://mui.com/material-ui/material-icons/?query=sell&selected=Sell linking to RedBubble
AccountBalanceWallet Icon - https://mui.com/material-ui/material-icons/?query=AccountBalanceWallet&selected=AccountBalanceWallet linking to Open Collective
[Mui Core](https://mui.com/material-ui/material-icons/) does not include official icons for both references, so I chose similar ones to represent the main goal of each site (selling, funding). With this approach we don't need to create new assets for them, until someday they could be part of that library. If the …
=> :bento: Add Open Collective and Redbubble links

CONTRIBUTING.md
The current Contribution Guide refers to a project team that it is no longer behind of this community. Referening to the Community team under the contact email could help better to spread it and open the collaboration.
Align the content of the OPL to a better community, not just built by Red Hat.
=> :busts_in_silhouette: Update contact information

README.md
#2263 
We used to use Gitter for real-time chat, but have not done so for a long time, and now Gitter no longer even exists.  We need to remove remaining references to Gitter from OPL.  A big 🙏 Thank you to @Moosh-be 🙏  for raising issue #2263
=> Update README.md to remove reference to Gitter

DEVELOPING.md
Add a note to advise users which node / npm version to use.
Well, it does not solve it - but at least it is related to https://github.com/openpracticelibrary/openpracticelibrary/issues/2390
The problem is, that building the app locally does not seem to work with current node / npm versions. A respective note might save people some trial & error time - and maybe even lower the hurdle to contribute.
=> Add node version hint
